In [6]:
import numpy as np
from scipy.ndimage import label as CCL

In [5]:
def CalcQi(component, board):
    '''计算一块棋的气'''
    qi = 0    
    zeros = np.where(board == 0)   
    for n in range(len(zeros[0])):
        i,j = zeros[0][n], zeros[1][n]
        if i < np.min(component[0])-1 or i > np.max(component[0])+1: continue
        if j < np.min(component[1])-1 or j > np.max(component[1])+1: continue
        exit_flag = 0
        for offset in [[0, -1], [1, 0], [-1, 0], [0, 1]]:
            i2, j2 = i + offset[0], j + offset[1]
            if 0 <= i2 < MapL and 0 <= j2 < MapL:
                for m in range(len(component[0])):
                    if i2 == component[0][m] and component[1][m] == j2:
                        qi += 1
                        if (min(i,j)==0 or max(i,j)==MapL-1) and (min(i2,j2)==0 or max(i2,j2)==MapL-1):
                            qi += 0.15
                        exit_flag = True
                        break
            if exit_flag: break                
    return qi

def tizi(board):
    '''提子，返回提子的数量'''
    #print("tizi")
    tizi_nums = [0,0]
    board_0 = board.copy()
    for n, player in enumerate([1+step%2, 2-step%2]):
        board_1 = board_0 == player
        components = CCL(board_1)[0]
        for i in range(int(np.max(components))):
            component = np.where(components==i+1)
            if CalcQi(component, board) == 0: 
                tizi_nums[n] += np.shape(component)[1]
                if n: board[component] = 0
    return tizi_nums

In [2]:
arr = np.array([[0,1,0],[1,1,1],[0,1,0]])

In [7]:
CCL(arr)[0]

array([[0, 1, 0],
       [1, 1, 1],
       [0, 1, 0]])

In [16]:
a = np.array([[0,0,1,1,0,0],
              [0,0,0,1,0,0],
              [1,1,0,0,1,0],
              [0,0,0,1,0,0]])
b = CCL(a)[0]

In [17]:
components = np.where(b == 2)

In [18]:
components

(array([2, 2], dtype=int64), array([0, 1], dtype=int64))

In [15]:
b

(array([[0, 0, 1, 1, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [2, 2, 0, 0, 3, 0],
        [0, 0, 0, 4, 0, 0]]),
 4)

In [13]:
step = 52
for n, player in enumerate([1+step%2, 2-step%2]):
    print([n, player])

[0, 1]
[1, 2]


In [6]:
not 0 and 0

0

In [14]:
a = ()

In [15]:
a

()

In [19]:
a == ()

True